# Generated by Django 4.0.1 on 2022-08-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alter_category_created_alter_category_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='expires',
            new_name='due_date',
        ),
    ]
