version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: td_user
      POSTGRES_PASSWORD: td_paSS81
      POSTGRES_DB: todolist
    restart: always
    ports:
    - "5432:5432"

volumes:
  postgres_data:
